WIP: Bugfix: Addition / Multiplication of Zernike Jacobi matrices
JuliaApproximation/MultivariateOrthogonalPolynomials.jl pull request #123
Opened 2022-04-27 15:13 UTC by TSGut

This makes the fixes made in https://github.com/JuliaMatrices/InfiniteLinearAlgebra.jl/pull/103 also work for the Zernike Jacobi matrices.

2022-04-27 16:25 UTC, TSGut commented
I think this covers all the actions one may want to do with these operators for now. Ready to merge.

2022-04-27 18:41 UTC, TSGut commented
@dlfivefifty So what's the mechanism allowing for the use of `Z \ (x .* Z)` to call the jacobi matrices? That is still missing to make this implementation harmonize properly with the rest of the package.

2022-04-28 09:39 UTC, dlfivefifty commented
That should just work provided you overload `jacobimatrix(::Val{1}, ...)`:

https://github.com/JuliaApproximation/HarmonicOrthogonalPolynomials.jl/blob/869f0313a180a7352f0bb8b554399d7b863aef83/src/multivariateops.jl#L37

2022-04-29 21:05 UTC, TSGut commented
I figured out why it wasn't working. Basically, the stuff you linked at one point requires copy(jacobimatrix(Val(1),Z)) to work but that wasn't working because copy wasn't defined for the type I made to hide the excessive type printout.

I think I fixed it.

2022-04-29 21:45 UTC, TSGut commented
@dlfivefifty This is ready to merge.

2022-04-30 07:51 UTC, dlfivefifty requested changes

2022-04-30 07:51 UTC, dlfivefifty commented on src/disk.jl
> +        dat = BlockHcat(ZernikeJacobimatrixBandsX{T}(Z))
What is BlockHcat doing here?

2022-04-30 08:11 UTC, TSGut commented on src/disk.jl
> +        dat = BlockHcat(ZernikeJacobimatrixBandsX{T}(Z))
If it's not wrapped in BlockHcat the addition and multiplication of Jacobi matrices from here https://github.com/JuliaMatrices/InfiniteLinearAlgebra.jl/pull/103 doesn't work.

So this works:
```julia
k = mortar(Base.OneTo.(oneto(∞)))
n = mortar(Fill.(oneto(∞), oneto(∞)))
dat = BlockHcat(
    BlockBroadcastArray(hcat, float.(k), Zeros((axes(n, 1),)), float.(n)),
    Zeros((axes(n, 1), Base.OneTo(3))),
    Zeros((axes(n, 1), Base.OneTo(3))))
M = BlockBandedMatrices._BandedBlockBandedMatrix(dat', axes(k, 1), (1, 1), (1, 1))
Ms = Symmetric(M)

# works
Ms+Ms
Ms*Ms
```

but if you instead do this which is the same matrix written differently.

```julia
dat = BlockBroadcastArray(hcat, float.(k), Zeros((axes(n, 1),)), float.(n))
M = BlockBandedMatrices._BandedBlockBandedMatrix(dat', axes(k, 1), (-1, 1), (1, 1))
Ms = Symmetric(M)

# doesn't work
Ms+Ms
Ms*Ms
```

I thought that's because you intended the _BandedBlockBandedMatrix to be used with BlockVCat/HCat and use the structure of that type but given that you're asking the question I take it these are actually bugs.

2022-05-03 10:19 UTC, TSGut commented
By comparing with the Triangle code, I've decided it's better to not have the custom type for the Jacobi matrices for now, especially since it just leads to harder to read and debug code and actually slows things down for an enduser.

The tests I implemented here won't pass because of this change until the addition bug mentioned here https://github.com/JuliaApproximation/MultivariateOrthogonalPolynomials.jl/pull/123#discussion_r862328705 has been resolved.

2022-05-04 09:47 UTC, TSGut commented
@dlfivefifty This is ready to merge and can now do polynomial multiplication operators. I'm pretty sure the coverage reduction is an artifact due to a reduction in lines of code as the patch diff is 100%.

2022-05-04 09:48 UTC, merged